# Generated by Django 4.1.3 on 2022-11-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=50)),
                ("group", models.CharField(max_length=50)),
                ("invite_reason", models.CharField(max_length=64)),
                ("images", models.ImageField(default="", upload_to="images")),
            ],
        ),
    ]
